import { NextAuthProvider } from "@/lib/providers";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { ToastProvider } from "@/providers/ToastProvider";
import ProgressBarProviders from "@/providers/ProgressBarProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jumpstart Retail",
  description: "Generated by create next app",
  icons: {
    icon: "jumpstart.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <NextAuthProvider>
        <ReactQueryProvider>
          <body className={montserrat.className}>
            <ToastProvider />
            <main>{children}</main>
          </body>
        </ReactQueryProvider>
      </NextAuthProvider>
    </html>
  );
}
