import { NextAuthProvider } from "@/lib/providers";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <ReactQueryProvider>
          <body className={montserrat.className}>{children}</body>
        </ReactQueryProvider>
      </NextAuthProvider>
    </html>
  );
}
